spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokemon_database
    username: username
    password: password
  jpa:
    show-sql: true # Pour afficher les requêtes SQL dans la console
    hibernate:
      ddl-auto: create-drop # Pour ne pas que Hibernate crée les tables à notre place
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui.path: /swagger
