spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/default_database
    username: username
    password: password
  jpa:
    show-sql: true # Pour afficher les requêtes SQL dans la console
    hibernate:
      ddl-auto: none # Pour que Spring créer le schèma en lançant les migrations
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui.path: /docs
